#!/usr/bin/env python3
"""trivy-report — turn verbose Trivy JSON into a short, PR-friendly Markdown summary.

Trivy's default output is great in a terminal but noisy in a pull request or a CI
job summary. This reads `trivy ... -f json` output and prints a compact Markdown
report: a severity count table plus a prioritized list of the vulnerabilities that
actually have a fix available.

Usage:
    trivy image -f json myimage:latest > scan.json
    python trivy_report.py scan.json
    python trivy_report.py scan.json -o report.md --fail-on HIGH

With no file argument it reads from stdin, so it pipes cleanly:
    trivy image -f json myimage:latest | python trivy_report.py
"""

import argparse
import json
import sys

# Highest severity first. Index in this list = priority (lower = worse).
SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]
SEVERITY_RANK = {name: i for i, name in enumerate(SEVERITY_ORDER)}


def load_report(path):
    """Load Trivy JSON from a file path, or from stdin when path is None/'-'."""
    if path in (None, "-"):
        raw = sys.stdin.read()
    else:
        with open(path, "r", encoding="utf-8") as fh:
            raw = fh.read()
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        sys.exit(f"error: input is not valid JSON ({exc}). "
                 f"Did you run trivy with `-f json`?")


def collect_vulnerabilities(report):
    """Flatten every vulnerability across all Results into one list."""
    vulns = []
    for result in report.get("Results", []) or []:
        target = result.get("Target", "")
        for v in result.get("Vulnerabilities", []) or []:
            v["_target"] = target
            vulns.append(v)
    return vulns


def severity_counts(vulns):
    counts = {name: 0 for name in SEVERITY_ORDER}
    for v in vulns:
        sev = (v.get("Severity") or "UNKNOWN").upper()
        counts[sev] = counts.get(sev, 0) + 1
    return counts


def worst_severity(vulns):
    """Return the most severe severity present, or None if there are no vulns."""
    ranks = [SEVERITY_RANK.get((v.get("Severity") or "UNKNOWN").upper(), 99)
             for v in vulns]
    if not ranks:
        return None
    return SEVERITY_ORDER[min(ranks)]


def build_markdown(report, vulns):
    artifact = report.get("ArtifactName", "unknown")
    artifact_type = report.get("ArtifactType", "")
    counts = severity_counts(vulns)
    total = sum(counts.values())

    lines = []
    lines.append(f"## 🛡️ Trivy scan report — `{artifact}`")
    if artifact_type:
        lines.append(f"_Type: {artifact_type}_")
    lines.append("")

    if total == 0:
        lines.append("✅ **No vulnerabilities found.**")
        return "\n".join(lines) + "\n"

    # Severity summary table.
    lines.append("| Severity | Count |")
    lines.append("| --- | --- |")
    emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡",
             "LOW": "🔵", "UNKNOWN": "⚪"}
    for sev in SEVERITY_ORDER:
        if counts[sev]:
            lines.append(f"| {emoji[sev]} {sev} | {counts[sev]} |")
    lines.append(f"| **Total** | **{total}** |")
    lines.append("")

    # Prioritized list of fixable vulnerabilities.
    fixable = [v for v in vulns if v.get("FixedVersion")]
    fixable.sort(key=lambda v: SEVERITY_RANK.get(
        (v.get("Severity") or "UNKNOWN").upper(), 99))

    if fixable:
        lines.append(f"### 🔧 Fixable vulnerabilities ({len(fixable)})")
        lines.append("")
        lines.append("| Severity | Package | Installed | Fixed in | CVE |")
        lines.append("| --- | --- | --- | --- | --- |")
        for v in fixable:
            sev = (v.get("Severity") or "UNKNOWN").upper()
            pkg = v.get("PkgName", "")
            installed = v.get("InstalledVersion", "")
            fixed = v.get("FixedVersion", "")
            cve = v.get("VulnerabilityID", "")
            url = v.get("PrimaryURL", "")
            cve_cell = f"[{cve}]({url})" if url else cve
            lines.append(
                f"| {emoji.get(sev, '⚪')} {sev} | `{pkg}` | "
                f"{installed} | **{fixed}** | {cve_cell} |")
        lines.append("")
    else:
        lines.append("_No fixes are available yet for the detected "
                     "vulnerabilities._")
        lines.append("")

    lines.append("<sub>Generated by "
                 "[trivy-report](https://github.com/) · "
                 "prioritizes vulnerabilities that have an upstream fix.</sub>")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Turn Trivy JSON output into a compact Markdown report.")
    parser.add_argument("input", nargs="?", default="-",
                        help="Trivy JSON file (default: read from stdin)")
    parser.add_argument("-o", "--output",
                        help="write the report to a file instead of stdout")
    parser.add_argument("--fail-on", choices=SEVERITY_ORDER,
                        help="exit with code 1 if a vulnerability at or above "
                             "this severity is present (useful to gate CI)")
    args = parser.parse_args(argv)

    report = load_report(args.input)
    vulns = collect_vulnerabilities(report)
    markdown = build_markdown(report, vulns)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(markdown)
        print(f"Report written to {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(markdown)

    if args.fail_on:
        worst = worst_severity(vulns)
        if worst is not None and \
                SEVERITY_RANK[worst] <= SEVERITY_RANK[args.fail_on]:
            print(f"Failing: found {worst} (threshold {args.fail_on})",
                  file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
